# Generated by Django 5.2.1 on 2025-10-03 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_notification_usernotificationread'),
    ]

    operations = [
        migrations.AddField(
            model_name='counsellingstatus',
            name='allotment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='counsellingstatus',
            name='allotment_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='counsellingstatus',
            name='allotted_college',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='counsellingstatus',
            name='allotted_course',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='counsellingstatus',
            name='current_stage',
            field=models.CharField(default='Registration Completed', max_length=200),
        ),
    ]
